<p>
The download of Simple is separated into several
distinct resources. This is done to separate the
core API and supplemental packages.
This keeps the size of each resource small and facilitates
the download of third party packages. The resources below
represent the current downloads available.</p>
<h3>Download</h3>
<p>
<p>
The primary download for Simple @core.version@ contains the entire source tree for the core API. As well as the source tree this contains an Ant build system which enables the source to be compiled and also contains the javadoc documentation for the framework.</p>
<ul>
<li>Download:
<a href='/download/download.php?version=@core.version@&package=simple-@core.version@.tar.gz'><b>simple-@core.version@.tar.gz</b></a></li>
<li>Download:
<a href='/download/download.php?version=@core.version@&package=simple-@core.version@.zip'><b>simple-@core.version@.zip</b></a></li>
</ul>
<p>
To leverage the many frameworks built on the Java Servlet API a servlet adaptation layer has been developed. This is currently in the very early stages of development. However it is at a stage where it is compliant enough to run the Apache Wicket examples, which is bundled with the servlet container. Any bugs or feedback that can be provided is always greatly appreciated.
<ul>
<li>Download:
<a href='/download/download.php?version=@servlet.version@&package=simple-servlet-@servlet.version@.tar.gz'><b>simple-servlet-@servlet.version@.tar.gz</b></a></li>
<li>Download:
<a href='/download/download.php?version=@servlet.version@&package=simple-servlet-@servlet.version@.zip'><b>simple-servlet-@servlet.version@.zip</b></a></li>
</ul>
<p>
For REST based services there is an XML serialization framework that can be used to read and write Java objects as XML. This provides a very lightweight and powerful means of implementing REST based web services. The <a href="http://simple.sourceforge.net/">Simple XML Serialization</a> framework can be downloaded with the following link.
<ul>
<li>Download:
<a href='http://simple.sourceforge.net/download.php'><b>simple-xml-@xml.version@.tar.gz</b></a></li>
</ul>

